c1:
  - action: start
    device: Steam
    level: min
  
  - delay: 5s
  
  - action: start
    device: Hotwater
    level: max
  
  - delay: 5s
  
  - action: start
    device: Vacuum
    level: med
  
  - delay: 20m
  
  - action: stop
    device: All
