actions:
- type: start
  device: Steam
  level: min
- type: delay
  amount: 30
  unit: sec
- type: stop
  device: Steam
- type: delay
  amount: 30
  unit: min
- type: start
  device: Hotwater
  level: med
- type: delay
  amount: 30
  unit: min
- type: start
  device: Vacuum
  level: max
