actions:
- type: start
  device: Steam
  level: med
- type: delay
  amount: 10
  unit: sec
- type: start
  device: Vacuum
  level: med
- type: delay
  amount: 10
  unit: sec
- type: stop
  device: All
